services:
  postgres:
    image: postgres:17-alpine
    container_name: ynab-investments-db
    environment:
      POSTGRES_DB: ynab_investments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: ynab-investments-adminer
    ports:
      - '8080:8080'
    depends_on:
      - postgres
    restart: unless-stopped

volumes:
  postgres_data:
