# YNAB Investment Sync Configuration
# This file tells the system which YNAB budget and accounts to sync with your investments.
# This is a YAML file that should be hosted at a publicly accessible URL.
# Set the INVESTMENTS_CONFIG_FILE_URL environment variable to point to your hosted file.

# Your YNAB Budget ID (you can find this in YNAB's URL when viewing your budget)
budget: 'your-ynab-budget-id'

# Optional: Custom sync schedule (if not specified, defaults to weekly on Sunday at 9 PM UTC)
schedule:
  sync_time: 9pm # Time to sync investments (in your local timezone)
  sync_frequency: daily # How often to sync investments (daily, weekly, monthly)

# List your investment accounts below
accounts:
  # First Investment Account (e.g., Brokerage Account)
  - account_id: 'your-ynab-account-id-1' # The YNAB account ID to sync to
    holdings:
      AAPL: 10.5 # Apple
      MSFT: 25.0 # Microsoft
      GOOGL: 5.0 # Google
      NVDA: 12.0 # Nvidia
      NSQE.DE: 15.0 # German market

  # Second Investment Account (e.g., Crypto Wallet)
  - account_id: 'your-ynab-account-id-2' # The YNAB account ID to sync to
    holdings:
      BTC: 0.5 # Bitcoin
      ETH: 2.0 # Ethereum
      ADA: 1000.0 # Cardano
