packages:
  - apps/*

hoist: false

nodeLinker: hoisted

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
  - esbuild
  - nx
  - oxc-resolver
  - unrs-resolver
  - vue-demi
