packages:
  - apps/*

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@parcel/watcher'
  - '@scarf/scarf'
  - '@swc/core'
  - esbuild
  - nx
  - unrs-resolver
  - vue-demi

hoist: false
nodeLinker: 'hoisted'
